### ISSUE TITLE
Enhancement: Add eclude range to scope

### ISSUE THREAD

**Issue by d-strobel** [d-strobel/ansible-collection-windows-dhcp#2]
Add exclude range to scope module:

Suggestion:
```yaml
exlude_ranges:
  - start: 10.10.51.55
    end: 10.10.51.60
  - start: 10.10.51.55
    end: 10.10.51.60
```
